//! # kiln-builtins
//!
//! Runtime builtins for synth-compiled WebAssembly on embedded targets.
//!
//! This crate provides the C ABI surface that synth-compiled ELF binaries
//! call into for host intrinsics, memory management, and WASI dispatch.
//! It is `no_std` compatible and targets bare-metal / RTOS environments
//! (Cortex-M via gale/Zephyr).
//!
//! ## Functions
//!
//! - [`__meld_dispatch_import`] — Routes import calls to WASI/host handlers
//! - [`__meld_get_memory_base`] — Returns linear memory base address
//! - [`cabi_realloc`] — Canonical ABI memory allocator

#![no_std]

use core::sync::atomic::{AtomicU32, Ordering};

#[cfg(not(test))]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

/// Bump allocator pointer for cabi_realloc.
/// Starts at a configurable offset within linear memory.
static BUMP_PTR: AtomicU32 = AtomicU32::new(0);

/// Initialize the bump allocator with a starting offset.
///
/// Must be called before any `cabi_realloc` calls. The offset should point
/// to free space within linear memory (typically after data segments).
#[unsafe(no_mangle)]
pub extern "C" fn __kiln_builtins_init(heap_start: u32) {
    BUMP_PTR.store(heap_start, Ordering::Release);
}

/// Called by synth-compiled code to dispatch an import call.
///
/// Synth generates: `MOV R0, #import_index; BL __meld_dispatch_import`
///
/// The import index maps to a WASI or host function. The import table
/// (generated by meld via `--emit-import-map`) maps indices to
/// module/function names. For Phase 1, this is a stub returning 0.
#[unsafe(no_mangle)]
pub extern "C" fn __meld_dispatch_import(import_index: u32) -> u32 {
    // Phase 1: stub — returns 0 for all imports.
    // Phase 2: read .meld_import_table, match to handler, dispatch.
    let _ = import_index;
    0
}

/// Returns the base address of WASM linear memory.
///
/// The linker provides `__wasm_memory_start` as the base of the
/// linear memory section in the ELF binary.
#[unsafe(no_mangle)]
pub extern "C" fn __meld_get_memory_base() -> *mut u8 {
    unsafe extern "C" {
        static __wasm_memory_start: u8;
    }
    unsafe { &raw const __wasm_memory_start as *mut u8 }
}

/// Canonical ABI allocator for linear memory.
///
/// Called by adapter code (generated by meld) to allocate space for
/// strings, lists, records, and other compound types. Uses a simple
/// bump allocator within linear memory bounds.
///
/// # Parameters
/// - `old_ptr`: Previous allocation pointer (0 for new allocation)
/// - `old_size`: Size of previous allocation (0 for new allocation)
/// - `align`: Required alignment (must be power of 2)
/// - `new_size`: Requested allocation size in bytes
///
/// # Returns
/// Offset from memory base of the allocated region, or 0 on failure.
#[unsafe(no_mangle)]
pub extern "C" fn cabi_realloc(
    old_ptr: u32,
    old_size: u32,
    align: u32,
    new_size: u32,
) -> u32 {
    let _ = (old_ptr, old_size);

    if new_size == 0 {
        return 0;
    }

    // Align must be power of 2
    let align = if align == 0 { 1 } else { align };

    loop {
        let current = BUMP_PTR.load(Ordering::Acquire);
        if current == 0 {
            // Not initialized
            return 0;
        }

        // Align up
        let aligned = (current + align - 1) & !(align - 1);
        let next = aligned + new_size;

        match BUMP_PTR.compare_exchange_weak(
            current,
            next,
            Ordering::AcqRel,
            Ordering::Acquire,
        ) {
            Ok(_) => return aligned,
            Err(_) => continue, // Retry on contention
        }
    }
}
