//! # kiln-builtins
//!
//! Runtime builtins for synth-compiled WebAssembly on embedded targets.
//!
//! This crate provides the C ABI surface that synth-compiled ELF binaries
//! call into for host intrinsics, memory management, and WASI dispatch.
//! It is `no_std` compatible and targets bare-metal / RTOS environments
//! (Cortex-M via gale/Zephyr).
//!
//! ## Functions
//!
//! - [`__meld_dispatch_import`] — Routes import calls to WASI/host handlers
//! - [`__meld_get_memory_base`] — Returns linear memory base address
//! - [`cabi_realloc`] — Canonical ABI memory allocator

#![cfg_attr(not(test), no_std)]

use core::sync::atomic::{AtomicU32, Ordering};

#[cfg(not(test))]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

/// Bump allocator pointer for cabi_realloc.
/// Starts at a configurable offset within linear memory.
static BUMP_PTR: AtomicU32 = AtomicU32::new(0);

/// Initialize the bump allocator with a starting offset.
///
/// Must be called before any `cabi_realloc` calls. The offset should point
/// to free space within linear memory (typically after data segments).
#[unsafe(no_mangle)]
pub extern "C" fn __kiln_builtins_init(heap_start: u32) {
    BUMP_PTR.store(heap_start, Ordering::Release);
}

/// Called by synth-compiled code to dispatch an import call.
///
/// Synth generates: `MOV R0, #import_index; BL __meld_dispatch_import`
///
/// The import index maps to a WASI or host function. The import table
/// (generated by meld via `--emit-import-map`) maps indices to
/// module/function names. For Phase 1, this is a stub returning 0.
#[unsafe(no_mangle)]
pub extern "C" fn __meld_dispatch_import(import_index: u32) -> u32 {
    // Phase 1: stub — returns 0 for all imports.
    // Phase 2: read .meld_import_table, match to handler, dispatch.
    let _ = import_index;
    0
}

/// Returns the base address of WASM linear memory.
///
/// The linker provides `__wasm_memory_start` as the base of the
/// linear memory section in the ELF binary.
#[cfg(not(test))]
#[unsafe(no_mangle)]
pub extern "C" fn __meld_get_memory_base() -> *mut u8 {
    unsafe extern "C" {
        static __wasm_memory_start: u8;
    }
    unsafe { &raw const __wasm_memory_start as *mut u8 }
}

/// Canonical ABI allocator for linear memory.
///
/// Called by adapter code (generated by meld) to allocate space for
/// strings, lists, records, and other compound types. Uses a simple
/// bump allocator within linear memory bounds.
///
/// # Parameters
/// - `old_ptr`: Previous allocation pointer (0 for new allocation)
/// - `old_size`: Size of previous allocation (0 for new allocation)
/// - `align`: Required alignment (must be power of 2)
/// - `new_size`: Requested allocation size in bytes
///
/// # Returns
/// Offset from memory base of the allocated region, or 0 on failure.
#[unsafe(no_mangle)]
pub extern "C" fn cabi_realloc(
    old_ptr: u32,
    old_size: u32,
    align: u32,
    new_size: u32,
) -> u32 {
    let _ = (old_ptr, old_size);

    if new_size == 0 {
        return 0;
    }

    // Align must be power of 2
    let align = if align == 0 { 1 } else { align };

    loop {
        let current = BUMP_PTR.load(Ordering::Acquire);
        if current == 0 {
            // Not initialized
            return 0;
        }

        // Align up: (current + align - 1) & !(align - 1)
        // Safe because align is non-zero (set to 1 above if 0)
        let aligned = (current.wrapping_add(align - 1)) & !(align - 1);
        let next = match aligned.checked_add(new_size) {
            Some(n) => n,
            None => return 0, // Overflow — allocation would exceed u32 range
        };

        match BUMP_PTR.compare_exchange_weak(
            current,
            next,
            Ordering::AcqRel,
            Ordering::Acquire,
        ) {
            Ok(_) => return aligned,
            Err(_) => continue, // Retry on contention
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn reset_bump() {
        BUMP_PTR.store(0, Ordering::SeqCst);
    }

    #[test]
    fn test_cabi_realloc_uninitialized_returns_zero() {
        reset_bump();
        assert_eq!(cabi_realloc(0, 0, 1, 16), 0);
    }

    #[test]
    fn test_cabi_realloc_zero_size_returns_zero() {
        reset_bump();
        __kiln_builtins_init(0x1000);
        assert_eq!(cabi_realloc(0, 0, 1, 0), 0);
    }

    #[test]
    fn test_cabi_realloc_basic_allocation() {
        reset_bump();
        __kiln_builtins_init(0x1000);
        let ptr = cabi_realloc(0, 0, 1, 16);
        assert_eq!(ptr, 0x1000);
        // Next allocation follows
        let ptr2 = cabi_realloc(0, 0, 1, 8);
        assert_eq!(ptr2, 0x1010);
    }

    #[test]
    fn test_cabi_realloc_alignment() {
        reset_bump();
        __kiln_builtins_init(0x1001); // Misaligned start
        // Request 8-byte alignment
        let ptr = cabi_realloc(0, 0, 8, 4);
        assert_eq!(ptr, 0x1008); // Aligned up to 8
        // Next with 4-byte alignment
        let ptr2 = cabi_realloc(0, 0, 4, 4);
        assert_eq!(ptr2, 0x100C); // 0x1008 + 4 = 0x100C, already 4-aligned
    }

    #[test]
    fn test_cabi_realloc_overflow_returns_zero() {
        reset_bump();
        __kiln_builtins_init(u32::MAX - 10);
        let ptr = cabi_realloc(0, 0, 1, 100);
        assert_eq!(ptr, 0); // Would overflow u32
    }

    #[test]
    fn test_dispatch_import_stub() {
        assert_eq!(__meld_dispatch_import(0), 0);
        assert_eq!(__meld_dispatch_import(42), 0);
        assert_eq!(__meld_dispatch_import(u32::MAX), 0);
    }
}

// ============================================================================
// Kani proofs
// ============================================================================

#[cfg(kani)]
mod proofs {
    use super::*;

    #[kani::proof]
    fn cabi_realloc_never_overflows() {
        let heap_start: u32 = kani::any();
        let align: u32 = kani::any();
        let new_size: u32 = kani::any();

        // Preconditions
        kani::assume(heap_start > 0); // initialized
        kani::assume(align <= 4096); // reasonable alignment
        kani::assume(align == 0 || (align & (align - 1)) == 0); // power of 2 or 0

        BUMP_PTR.store(heap_start, Ordering::SeqCst);
        let result = cabi_realloc(0, 0, align, new_size);

        // Post-conditions
        if result != 0 {
            // Result must be >= heap_start
            assert!(result >= heap_start);
            // Result must be aligned
            let effective_align = if align == 0 { 1 } else { align };
            assert!(result % effective_align == 0);
            // result + new_size must not overflow (checked_add returned Some)
            assert!(result as u64 + new_size as u64 <= u32::MAX as u64 + 1);
        }
    }

    #[kani::proof]
    fn cabi_realloc_alignment_correct() {
        let heap_start: u32 = kani::any();
        kani::assume(heap_start > 0 && heap_start < 0x1000_0000);

        // Test all power-of-2 alignments from 1 to 256
        let align_shift: u32 = kani::any();
        kani::assume(align_shift <= 8);
        let align = 1u32 << align_shift;

        let new_size: u32 = kani::any();
        kani::assume(new_size > 0 && new_size <= 1024);

        BUMP_PTR.store(heap_start, Ordering::SeqCst);
        let result = cabi_realloc(0, 0, align, new_size);

        if result != 0 {
            assert!(result % align == 0, "Result not properly aligned");
        }
    }

    #[kani::proof]
    fn dispatch_import_always_returns_zero() {
        let idx: u32 = kani::any();
        assert_eq!(__meld_dispatch_import(idx), 0);
    }
}
